# Generated by Django 4.0.4 on 2022-07-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyid', models.CharField(max_length=100)),
                ('emailList', models.CharField(max_length=20000)),
                ('allowedbyall', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyid', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('json', models.TextField()),
                ('anonymous', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('surveyname', models.CharField(max_length=100)),
                ('surveyid', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('json', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('private_key', models.CharField(max_length=100)),
            ],
        ),
    ]
