# Generated by Django 4.0.4 on 2022-07-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_management_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='endtime',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='starttime',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
